### PR TITLE
Fix button events being sent when super is held

### LINKED ISSUE #686: [BUG] Super + Right click passes right through to the application
Holding super to resize, then clicking rightclick passes the rightclick through to the application

### PR DESCRIPTION
**Pull request by JCapucho**
Fixes #686

Previously when doing Super+{Left,Right} Click the compositor would still send the button event to the client, for left click this didn't cause issues most of the time but for right click this caused many issues because it would usually open a context menu which would cause the resize to stop immediately.

This PR fixes the issue by not sending any button events if the logo key is held.

### CODE REVIEW

File: src/input/mod.rs [hunk 1]
```diff
@@ -972,17 +980,19 @@ impl State {
...
-                        self,
-                        &ButtonEvent {
-                            button,
-                            state: event.state(),
-                            serial,
-                            time: event.time_msec(),
-                        },
-                    );
-                    ptr.frame(self);
+                    if pass_event {
```
Comment (Drakulix) [inline src/input/mod.rs:983]: This isn't entirely correct, as this would still send the `ButtonReleased`-event without the client seeing a `ButtonPressed`-event previously.

You might want to take inspiration from `surpressed_keys` for keyboard-input. This will need a similar solution for mouse buttons.

**Review by Drakulix — CHANGES_REQUESTED** [review]
Looks mostly good to me, except for mismatched button events.

File: src/input/mod.rs (hunk 1 above)
Comment (JCapucho) [reply src/input/mod.rs:983]: I've been trying to fix this for a while and I think I might have taken the wrong approach, contrary to the keyboard `input` where we can intercept the event from the client, we must always send the `button` event because it will be sent to the `PointerGrab`, otherwise it will get stuck.

My idea is that the interception code gets moved to the `MoveGrab` and `ResizeForkGrab` where a new boolean field gets added for whether they are grabs resulting from a Super + {Left, Right} Click or not, And if they are the `button` handler doesn't pass the event to the client.

What do you think @Drakulix ?

Comment (JCapucho) [reply src/input/mod.rs:985]: I've actually implemented the suppress functionality in the grabs and ended up needing to do both the current approach of suppressing pressed events in `process_input` and release events in the grabs, because the grab is only added in the next idle cycle.

However this still seems to be not enough because in case a grab is not set there exists nothing to suppress the release event. So it seems like something like `suppressed_keys` is also needed.

Comment (JCapucho) [reply src/input/mod.rs:1007]: I've finished adding code to suppress buttons that do not trigger a grab.

Honestly the code is not ideal, there's a lot of argument drilling but I don't know how to architect it better.

File: src/input/mod.rs [hunk 2]
```diff
@@ -849,15 +863,22 @@ impl State {
                                             if let Some(surface) =
                                                 target.toplevel().map(Cow::into_owned)
                                             {
+                                                // If the logo is held then the pointer event is
+                                                // aimed at the compositor and shouldn't be passed
+                                                // to the application.
+                                                pass_event = false;
```
Comment (Drakulix) [inline src/input/mod.rs:869]: We should add the button to supressed_buttons right once we decided to not pass the event. Otherwise we might get mismatches, as it isn't deterministic when the idle_callbacks will run. Also having this in the `_`-match clause and `dispatch_grab` seems highly repetitive. We know already that we will skip the event here.

Though I would like to chance even this logic. Currently we discard every mouse button, if super as held, but we only need to discard those, that we will handle ourselves. So we should not prevent middle-clicks and other buttons, just left and right clicks.

Comment (Drakulix) [reply src/input/mod.rs:869]: Then we should also not need to add this to the grab code, which I really want to avoid as that is leaking abstractions left and right.

**Review by Drakulix — COMMENTED** [review]
Still not 100% right, but thanks for working on this!

File: src/input/mod.rs (hunk 2 above)
Comment (JCapucho) [reply src/input/mod.rs:869]: > Then we should also not need to add this to the grab code, which I really want to avoid as that is leaking abstractions left and right.

The problem is that `ptr.button` needs to be called if there is a grab because otherwise it won't receive the release event and it will be stuck moving/resizing.

And at that point the grab is the one that forwards to the client so it must be the one responsible for suppressing the button.

Comment (Drakulix) [reply src/input/mod.rs:869]: We could also release the grab inside of the input-handler. Its drop code will be called either way.

**Comment by JCapucho** [comment]
I've switched the code to unset the grab instead of tracking the suppression status on the grab this greatly simplifies the code. I've also change the code so that the suppression is only done in the buttons handled by the compositor by pulling the match out.

I'm sure the code isn't good enough yet but just wanted to know if the overall structure is sound. And thank you for guiding me while implementing this :)

File: src/input/mod.rs [hunk 3]
```diff
@@ -845,40 +859,50 @@ impl State {
                                     // Don't check override redirect windows, because we don't set keyboard focus to them explicitly.
                                     // These cases are handled by the XwaylandKeyboardGrab.
                                     if let Some(target) = shell.element_under(pos, &output) {
-                                        if seat.get_keyboard().unwrap().modifier_state().logo {
+                                        if seat.get_keyboard().unwrap().modifier_state().alt {
```
Comment (Drakulix) [inline src/input/mod.rs:862]: Why change the modifier?

File: src/input/mod.rs [hunk 4]
```diff
@@ -969,20 +1001,25 @@ impl State {
...
+                            self,
+                            &ButtonEvent {
+                                button,
+                                state: event.state(),
+                                serial,
+                                time: event.time_msec(),
+                            },
+                        );
+                        ptr.frame(self);
+                    } else {
```
Comment (Drakulix) [inline src/input/mod.rs:1020]: Small nitpick here: Given we set the grab with an idle-callback unsetting any grab any time we don't pass events isn't wrong, but technically we only want to unset grabs on a `Released`-event.

```suggestion
                    } else if event.state() == ButtonState::Released {
```

**Review by Drakulix — COMMENTED** [review]
Looks mostly good to me know! Two small nitpicks, then this is ready for merge imo. Thanks for working on this!

File: src/input/mod.rs (hunk 3 above)
Comment (JCapucho) [reply src/input/mod.rs:862]: I changed it for testing because the logo key was being caught by my DE, didn't mean to commit it.

**Review by Drakulix — APPROVED** [review]
Thanks!
