### PR TITLE
Fix the windows shrinking after a drag-drop

### LINKED ISSUE #2285: Kitty floating window height reduces when moved
I belive it happened after update to 1.0.9 (arch linux), though i'm not sure.
While other widows moves normally (as shown with nemo in video), kitty snaps to cursor with it's title bar and gets smaller in height after moved. Video attached.
https://github.com/user-attachments/assets/78c19871-5d70-495c-bc10-16a8926b3e90

### PR DESCRIPTION
**Pull request by hojjatabdollahi**
SSD height is not currently taken into account, so dragging and dropping a window around will keep shrinking it.

https://github.com/user-attachments/assets/ffc6e53e-34f7-44a3-9b05-7ae8b119b924

Fixes https://github.com/pop-os/cosmic-comp/issues/2285 and https://github.com/pop-os/cosmic-comp/issues/2272
___
- [x] I have disclosed use of any AI generated code in my commit messages.
  - If you are using an LLM, and do not fully understand the changes it is making to the code base, do not create a PR.
  - In our experience, AI generated code often results in overly complex code that lacks enough context for a proper fix or feature inclusion. This results in considerably longer code reviews. Due to this, AI authored or partially authored PRs may be closed without comment.
- [x] I understand these changes in full and will be able to respond to review comments.
- [x] My change is accurately described in the commit message.
- [x] My contribution is tested and working as described.
- [x] I have read the [Developer Certificate of Origin](https://developercertificate.org/) and certify my contribution under its conditions.

### CODE REVIEW

File: src/shell/layout/floating/mod.rs [hunk 1]
```diff
@@ -686,7 +686,10 @@ impl FloatingLayout {
                 && let Some(pending_size) = window.pending_size()
             {
                 mapped_geometry.size = pending_size.as_local();
-            } else if let Some(server_size) = window.active_window().last_server_size() {
+            } else if let Some(mut server_size) = window.active_window().last_server_size() {
+                if let Some(ssd) = window.ssd_height(false) {
+                    server_size.h += ssd;
+                }
```
Comment (Drakulix) [inline src/shell/layout/floating/mod.rs]: I looked at this and wondered "shouldn't this also apply to `pending_size()` in the branch above.

Then I realized the issue here is, that the former uses a method on the `CosmicWindow`/`CosmicStack` (dispatched through `CosmicMapped`), which takes SSDs into account, while `last_server_size` gets called directly on the `CosmicSurface`.

Could you instead please add a `last_server_size` method to the former, which handle SSDs internally, rather than add the fix here?

**Review by Drakulix — CHANGES_REQUESTED** [review]

File: src/shell/layout/floating/mod.rs (hunk 1 above)
Comment (hojjatabdollahi) [reply src/shell/layout/floating/mod.rs]: Thank you. The previous fix wouldn't correctly handle stacked windows if tab height is different from SSD height.

**Review by Drakulix — APPROVED** [review]
Looks good now. Thanks!

**Review by jacobgkau — APPROVED** [review]
Was previously seeing this with Slack, and with any app while stacked; windows shrank after drag/drop, and after enabling/disabling tiling. All of those scenarios work properly with this fix.
