### PR TITLE
session: Make sure to mark the socket as CLOEXEC early

### LINKED ISSUE #2156: Xwayland inherits COSMIC_SESSION_SOCK fd, breaking keyboard input and DRM master
## Description

After upgrading `cosmic-comp` (first noticed with `0.1~1771890949`, still present in `0.1~1772192261`), keyboard input is almost entirely broken — only roughly every 5th keypress gets through. Mouse input works normally.

## Root cause

When `cosmic-comp` spawns Xwayland, the `COSMIC_SESSION_SOCK` file descriptor (fd 12) is not marked `CLOEXEC`. Xwayland inherits the fd, closes it, and reuses the fd number for its own memfd (`/memfd:xwayland-shared`). After that, `cosmic-comp` can no longer communicate with `cosmic-session` over the session socket.

This causes:

- `Error reading from session socket`
- `Unable to become drm master, assuming unprivileged mode`
- Near-total loss of keyboard input (occasional keypresses leak through)

## Evidence

```
$ cat /proc/<cosmic-comp-pid>/environ | tr '\0' '\n' | grep COSMIC_SESSION_SOCK
COSMIC_SESSION_SOCK=12

$ ls -la /proc/<cosmic-comp-pid>/fd/12
lrwx------ 1 user user 64 ... /proc/<cosmic-comp-pid>/fd/12 -> '/memfd:xwayland-shared (deleted)'
```

fd 12 should be the session socket but has been replaced by Xwayland's shared memory segment.

Journal output at login:

```
cosmic-comp[3750]: Unable to become drm master, assuming unprivileged mode
cosmic-comp[3750]: Error reading from session socket
```

## Workaround

Disabling Xwayland restores full keyboard input:

```bash
echo "false" > ~/.config/cosmic/com.system76.CosmicComp/v1/xwayland_enabled
```

## Suggested fix

Set `FD_CLOEXEC` on the `COSMIC_SESSION_SOCK` fd before spawning child processes (Xwayland, etc.).

## Environment

- **OS:** Pop!_OS 24.04 (COSMIC)
- **cosmic-comp:** `0.1~1772192261~24.04~253b44f` (also affected: `0.1~1771890949~24.04~3f68eee`)
- **cosmic-session:** `1.0.0~1771619805~24.04~618624b`
- **Last known working:** cosmic-comp `0.1~1770407907~24.04~2ea1186` (pre-March 2 upgrade)
- **Keyboard:** Logitech K750
- **Mouse:** Logitech MX Master 2S
- **GPU:** Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef)

### PR DESCRIPTION
**Pull request by Drakulix**
Presumably fixes #2156 by making sure we set `cloexec` on the inherited socket before launching Xwayland.

Not sure why this would seemingly only a single person, but the previous logic definitely wasn't correct.

- [x] I have disclosed use of any AI generated code in my commit messages.
  - If you are using an LLM, and do not fully understand the changes it is making to the code base, do not create a PR.
  - In our experience, AI generated code often results in overly complex code that lacks enough context for a proper fix or feature inclusion. This results in considerably longer code reviews. Due to this, AI authored or partially authored PRs may be closed without comment.
- [x] I understand these changes in full and will be able to respond to review comments.
- [x] My change is accurately described in the commit message.
- [x] My contribution is tested and working as described.
- [x] I have read the [Developer Certificate of Origin](https://developercertificate.org/) and certify my contribution under its conditions.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -147,6 +147,9 @@ pub fn run(hooks: crate::hooks::Hooks) -> Result<(), Box<dyn Error>> {
     tracy_client::Client::start();
 
     utils::rlimit::increase_nofile_limit();
+    if let Err(err) = session::setup_socket() {
```
Comment (ids1024) [inline src/lib.rs:152]: It might be best to have comment here noting that it's important this is called before any subprocess is spawned, just to make sure we remember this in any future changes to this function. (Not that we're especially likely to add anything that starts a process to the top of `run`, but still.)

Otherwise, this change seems correct. If a bit awkward (as dealing with fd numbers from env vars will tend to be).

**Review by jacobgkau — DISMISSED** [review]
I've tested this on a few different systems (Intel, NVIDIA, AMD graphics). Input still works fine both before and after launching an Xwayland application (seemed like a semi-relevant thing to check based on the issue this presumably fixes).

Can re-approve after that comment's added if it's the only thing that changes.

File: src/lib.rs (hunk 1 above)
Comment (Drakulix) [reply src/lib.rs:152]: done.

**Comment by Drakulix** [comment]
Comment added

**Review by jacobgkau — APPROVED** [review]

**Review by ids1024 — APPROVED** [review]
